# HospitalA
server {
  listen 8443 ssl;
  server_name issuer-hospitala.local;

  ssl_certificate     /etc/nginx/certs/issuer-proxy.crt;
  ssl_certificate_key /etc/nginx/certs/issuer-proxy.key;

  # mTLS: require client cert signed by CA
  ssl_client_certificate /etc/nginx/certs/ca.crt;
  ssl_verify_client on;

  location / {
    proxy_pass http://issuer-hospitala:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

# HospitalB
server {
  listen 8443 ssl;
  server_name issuer-hospitalb.local;

  ssl_certificate     /etc/nginx/certs/issuer-proxy.crt;
  ssl_certificate_key /etc/nginx/certs/issuer-proxy.key;

  ssl_client_certificate /etc/nginx/certs/ca.crt;
  ssl_verify_client on;

  location / {
    proxy_pass http://issuer-hospitalb:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
